version: 2.1

orbs:
  node: circleci/node@5

workflows:
  my-workflow:
    jobs:
      - build-test-lint-frontend
      - build-test-lint-backend

jobs:
  build-test-lint-frontend:
    executor: node/default
    steps:
      - checkout
      - run:
          name: change to frontend directory
          command: cd frontend
      - run:
          name: install frontend dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: run frontend tests
          command: npm run test
      - run:
          name: run frontend linter
          command: npm run lint
      # - run:
      #     name: deploy frontend
      #     command: curl "https://api.render.com/deploy/srv-cq6iulcs1f4s73e4df0g?key=qyy55YltldM"

  build-test-lint-backend:
    executor: node/default
    steps:
      - checkout
      - run:
          name: change to backend directory
          command: cd backend
      - run:
          name: install backend dependencies
          command: npm install
      - run:
          name: run backend tests
          command: npm run test
      - run:
          name: run backend linter
          command: npm run lint
      # - run:
      #     name: deploy backend
      #     command: curl "https://api.render.com/deploy/srv-cq6iulcs1f4s73e4df0g?key=qyy55YltldM"
