version: 2.1

orbs:
  node: circleci/node@5

workflows:
  my-workflow:
    jobs:
      - build-test-lint-frontend
      - build-test-lint-backend

jobs:
  build-test-lint-frontend:
    executor: node/default
    steps:
      - checkout
      - run:
          name: change to frontend directory
          command: cd frontend
      - run:
          name: install frontend dependencies
          command: cd frontend
          command: npm install --legacy-peer-deps
      - run:
          name: run frontend tests
          command: cd frontend
          command: npm run test
      - run:
          name: run frontend linter
          command: cd frontend
          command: npm run lint

  build-test-lint-backend:
    executor: node/default
    steps:
      - checkout
      - run:
          name: change to backend directory
          command: cd backend
      - run:
          name: install backend dependencies
          command: cd backend
          command: npm install
      - run:
          name: run backend tests
          command: cd backend
          command: npm run test
      - run:
          name: run backend linter
          command: cd backend
          command: npm run lint
