version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test-backend:
    executor: node/default
    working_directory: ~/project/backend
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout:
          path: ~/project
      - run:
          name: install app dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: run tests
          command: npm run test
      - run:
          name: run linter
          command: npm run lint
workflows:
  build-and-test:
    jobs:
      - test-backend
